kind: pipeline
type: kubernetes
name: build-push

steps:
  - name: docker-build
    pull: if-not-exists
    image: plugins/docker
    environment:
      DOCKER_HOST: tcp://builder.default.svc.cluster.local:2375
    settings:
      repo: 192.168.49.2:5000/fstack-fe
      tags:
        - ${DRONE_COMMIT_SHA:0:8}
        - latest
      registry: 192.168.49.2:5000
      insecure: true
    when:
      event: [push]
---
kind: pipeline
type: kubernetes
name: deploy-prod

trigger:
  event:
    - promote
steps:
  - name: deploy-prod
    pull: if-not-exists
    image: bitnami/kubectl:1.33.1
    commands:
      - echo "$KUBE_CA_CERT" > /tmp/ca.crt
      - kubectl --server=$KUBE_SERVER --token=$KUBE_TOKEN --certificate-authority=/tmp/ca.crt get deployment
      - kubectl --server=$KUBE_SERVER --token=$KUBE_TOKEN --certificate-authority=/tmp/ca.crt set image deployment/fstack-fe fstack-fe=192.168.49.2:5000/fstack-fe:${DRONE_COMMIT_SHA:0:8}
    environment:
      KUBE_SERVER: https://kubernetes.default.svc
      KUBE_TOKEN:
        from_secret: kube_token
      KUBE_CA_CERT:
        from_secret: kube_ca_cert

# kube_token kube_ca_cert 都在drone repo settings里填写了